# Generated by Django 5.2.8 on 2025-11-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(max_length=255, unique=True)),
                ('user_id', models.CharField(max_length=255)),
                ('to_email', models.EmailField(max_length=254)),
                ('template_code', models.CharField(max_length=100)),
                ('variables', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempts', models.IntegerField(default=0)),
            ],
        ),
    ]
